version: '3'

services:
  php-apache:
    build: ./php-apache
    ports:
      - "8080:80"
    depends_on:
      - mariadb
    volumes:
      - ./src/:/var/www/html

  mariadb:
    image: mariadb:latest
    environment:
      MYSQL_DATABASE: informatikhighscores
      MYSQL_ROOT_PASSWORD: 8hHLM6y#2UqJ6N
    ports:
      - "3306:3306"

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      PMA_HOST: mariadb
      PMA_PORT: 3306
      MYSQL_ROOT_PASSWORD: 8hHLM6y#2UqJ6N
    ports:
      - "8082:80"
    depends_on:
      - mariadb